### ISSUE TITLE
Request for include a option to use with theme via functions php

### ISSUE THREAD

**Issue by ashikrnhq04** [themexpert/onepager#101]
Hi! onepager team you done a awesome revolutionary job  for building a website easily. it's very user friendly for both developer and user. Here is my request to implement a system to use this plugin with theme functions.php. cause as a developer it's something unprofessional to make a full site using plugin. hope you get the think. 

Regards

**Comment by nadimtuhin** [comment]
we are almost done here :)

**Comment by nadimtuhin** [comment]
#How to use 
Put this code inside functions.php after extracting tx-onepager.zip

``` php
require "tx-onepager/theme.php";
```
