### ISSUE TITLE
CONTACT FORM SHORTCODE

### ISSUE THREAD

**Issue by Sungod3000** [themexpert/onepager#102]
Hi,

where can I find the shortcode documentation for the address block? Since the email isnt linkable it would be great to have a small contact form in there but the documentation doesn't mention this block. Is there a develop enter documentation somewhere?

**Comment by nadimtuhin** [comment]
@Sungod3000 I am sorry I did not quite get your question. But you can enter any shortcode on any field of onepager :)

**Comment by Sungod3000** [comment]
exactly :D the question is where can I find a list of all the short codes to craft my own little contact form?

**Comment by nadimtuhin** [comment]
@Sungod3000 do you want a list of contact form 7 shortcodes inside onepager block? Also come in http://gitter.im/themexpert/onepager gitter chat

**Comment by Sungod3000** [comment]
ah thats it, thanks

**Comment by codexpert** [comment]
More clarification, OnePager doesn't give you any shortcode. You can use any 3pd plugins and their shortcode inside OnePager.
