### ISSUE TITLE
Integrating Timber Framework into onepager

### ISSUE THREAD

**Issue by JakeHenshall** [themexpert/onepager#103]
Hi,

Could you please look at integrating the Timber Framework into onepager so that we can build blocks using timber. Could you also look at allowing integration with Advanced Custom Fields within side of Timber.

https://github.com/jarednova/timber

**Comment by nadimtuhin** [comment]
timber support is coming well

**Comment by nadimtuhin** [comment]
@JakeHenshall :) here you go. Download this file unzip it inside your theme/onepager/blocks folder

https://gist.github.com/nadimtuhin/f91c41e0c6fc442d3483

**Comment by nadimtuhin** [comment]
closing it. let us know if it did not solve your problem
