### ISSUE TITLE
Customising the Admin

### ISSUE THREAD

**Issue by JakeHenshall** [themexpert/onepager#105]
Hi,

is there anyway that we can easily customise / white label that admin area to my own colours.

Thanks Jake.

**Comment by codexpert** [comment]
You mean the builder area?

**Comment by JakeHenshall** [comment]
Yeah i mean where the block are displayed. can we change the buttons etc... so that we can whitelabel it and make it our own.

**Comment by codexpert** [comment]
Yes you can by changing colors value from this file https://github.com/themexpert/onepager/blob/develop/engine/lithium/builder/variables.less

**Comment by nadimtuhin** [comment]
@JakeHenshall we need your help in this aspect. Please let us know how you would like this feature be implemented. Here are my ideas
1. additional css override
2. php functions to change text

anything else?

**Comment by JakeHenshall** [comment]
@nadimtuhin Yeah a CSS override would be ok, maybe if the plugin is detected it shows a field in backend or the live customizer

**Comment by codexpert** [comment]
We have had plan for this but not in our priority queue right now.
