### ISSUE TITLE
Indentation and Beautification

### ISSUE THREAD

**Issue by perroud** [themexpert/onepager#106]
Hello guys,
It can be perfectionism, but... why not a perfect re-indent html(5) output from One Pager? This idea reminds the old and nice [wp-beautifier](https://wordpress.org/plugins/wp-beautifier/) plugin, forgotten nowadays - unfortunately, doesn't work into newer versions of Wordpress. Scarcely, any wordpress plugin and/or theme can show a flawless output code. A good idea to have a built-in OnePager feature or fix the [wp-beautifier](https://wordpress.org/plugins/wp-beautifier/) as a fork, perhaps.

**Comment by nadimtuhin** [comment]
@perroud now a days we focus on minimizing html output by compressing. Can you please show us some grounds on why beautifying on production is helpful?

**Comment by perroud** [comment]
Dear @nadimtuhin,
Well... by compressing is offered by webserver +~ http protocol version. Is not a feature from other one.
First, gzip compressing. Second, js/css compress method, like Closure Compiler. Third, image compress for jpg/jpeg/png with any ways (few into WP, in fact). Indentation and/or beautification of html code is really good.

Re-indent and beautify, why? We have many ways to [posh](http://microformats.org/wiki/posh), usability, acessibility ~508/WAI~ and, of course, HTML5 give us a semantic html, oppositing a presentational structure available with HTML4.

**Comment by nadimtuhin** [comment]
@perroud got the idea. POSH looks like a great idea. Currently we are trying to maximize onepager usability with constant effort. We believe POSH will not make enough impact on usability. Maybe in future :) btw thanks for the idea.
