### ISSUE TITLE
Multisite error - I SOLVED (Custom Theme)

### ISSUE THREAD

**Issue by ricardowone** [themexpert/onepager#107]
Hi 
I found this error

Fatal error</b>:  Call to undefined function App\Assets\wp_scripts()

Fatal error: Call to undefined function App\Assets\wp_scripts() in /home/****_/**_****/zumpsites.com/public_html/wp-content/plugins/tx-onepager/app/Assets/BuildModeScripts.php on line 100

but in other installation work fine in same server

Thanks

**Comment by ricardowone** [comment]
Hi

Only try if is possible do it!

I changed file BuildModeScripts.php
line 100 to:

private function resetWpScriptQueue() {
    try{
        wp_scripts()->queue = [ ];
        wp_styles()->queue  = [ ];
    }catch(Expection $e){
    }
  }

not work for me

so

I comment two lines and work for me!

//      wp_scripts()->queue = [ ];
//      wp_styles()->queue  = [ ];

Maybe Help Users with Custom Themes

Thanks
Great Job

Ricardo
http://zumpsites.com
Brasil

**Comment by nadimtuhin** [comment]
@ricardowone thanks dude :v we will be releasing 1.2.5 in 3 days with a patch for this.

**Comment by ricardowone** [comment]
Great

I think create new blocks and share here if possible!

Nice Job

Thanks Again
Waiting your release ;)

Ricardo
http://zumpsites.com
Brasil
