### ISSUE TITLE
Fresh install blank page

### ISSUE THREAD

**Issue by moimael** [themexpert/onepager#109]
Hi, I just installed onepager 1.2.5 on a fresh wordpress 4.3.1 and I can't add or edit a page anymore.

It redirect me on a blank page. I tried to reinstall the plugin with same result.

Any pointers ?

Thanks !

**Comment by nadimtuhin** [comment]
sorry to hear that :( can you help us figure out the problem posting some screenshots?

**Comment by moimael** [comment]
Yes I'd be glad to help ! But there is not a lot to show, when I click edit or add on a page i'm redirected to a blank page (the console show an internal server error 500)

**Comment by nadimtuhin** [comment]
So you create a page>click load editor button>an empty page shows up right? If you are a developer please turn on your wp-config.php debug and in the network tab there should be something messed up. If you do not mind sending your wordpress username and password at `nadimtuhin @ themexpert dot com` we will check the problem. It will be a great help if you do so.

By the way we are working on automated error logging once its done its will be very easy to solve the problems.

**Comment by moimael** [comment]
`Fatal error: Call to undefined function League\Url\Components\mb_internal_encoding() in /var/www/html/wordpress/wp-content/plugins/tx-onepager/vendor/league/url/src/Components/Host.php on line 50`

Can this be related to the fact that my MySQL database is not in utf8 ?

**Comment by nadimtuhin** [comment]
thanks I am not sure what the problem is but certainly its not regarding database. I will let you know as soon as I get the reason of this

**Comment by nadimtuhin** [comment]
can you turn /var/www/html/wordpress/wp-content/plugins/tx-onepager/vendor/league/url/src/Components/Host.php on line 50 

``` php
    protected function saveInternalEncoding()
    {
        $this->encoding = mb_internal_encoding();
        if (stripos($this->encoding, 'utf-8') === false) {
            mb_internal_encoding('UTF-8');
        }
    }

```

to

``` php
    protected function saveInternalEncoding()
    {
        $this->encoding = mb_internal_encoding();
        if (stripos($this->encoding, 'utf-8') === false) {
           \mb_internal_encoding('UTF-8');
        }
    }
```

**Comment by nadimtuhin** [comment]
if this fixes the issue we will release 1.2.6 next week with some more goodies

**Comment by nadimtuhin** [comment]
update:

``` php
    protected function saveInternalEncoding()
    {
        $this->encoding = \mb_internal_encoding();
        if (stripos($this->encoding, 'utf-8') === false) {
           \mb_internal_encoding('UTF-8');
        }
    }
```

**Comment by moimael** [comment]
I found the issue
`sudo dnf install php-mbstring`
It seems that mb_internal_encoding() is not part of standard php distribution. Installing this package fixes my issue on Fedora (should work on CentOS too).

**Comment by moimael** [comment]
A warning in the install doc could be great :)

**Comment by nadimtuhin** [comment]
thanks a lot man :D we will put them in the faqs

also here are two free themes for onepager
https://www.themexpert.com/wordpress-themes/nimble
https://www.themexpert.com/wordpress-themes/notes

stay tuned for v2 coming with the best features available

**Comment by moimael** [comment]
Thanks for your reactivity :)
