### ISSUE TITLE
Footer block throw a bunch of errors

### ISSUE THREAD

**Issue by moimael** [themexpert/onepager#110]
Hi,

When adding a footer using onepage builder I get this : 

![capture d ecran de 2015-11-26 18-08-23](https://cloud.githubusercontent.com/assets/1479859/11442284/5bda6042-9514-11e5-8de7-cb44f9de29ce.png)

Thanks !

**Comment by nadimtuhin** [comment]
You can fix this by creating a menu in wordpress dashboard>appearance>menu. Also we are working on fixing this bug.

Let us know if it is not fixing your problem
