### ISSUE TITLE
Editor not working

### ISSUE THREAD

**Issue by liciadb** [themexpert/onepager#115]
![screen shot 2016-02-05 at 18 28 24](https://cloud.githubusercontent.com/assets/13622492/12855259/535d5628-cc36-11e5-862a-5df277e2c1d8.png)

**Comment by liciadb** [comment]
http://www.soapystrawberries.com/casalelebifore/

**Comment by codexpert** [comment]
Please give us access details so we can check. Email at support @ themexpert.com

**Comment by liciadb** [comment]
the problem is the plugin

WP Google Maps Shortcode

**Comment by codexpert** [comment]
Glad you figure it out :)

**Comment by liciadb** [comment]
Thank you!
