### ISSUE TITLE
Enable OnePager Not Working

### ISSUE THREAD

**Issue by paoloramos** [themexpert/onepager#116]
Hi,

When I click Enable OnePager on the Page editor, the page saves/publishes itself but other than that nothing happens. Am I doing something wrong?

I'm using WP 4.4.2 on WAMP at the moment.

Thanks,
Paolo.

**Comment by anakinjay** [comment]
Same issue for me on 4.4.2 using php's built in webserver.

**Comment by anakinjay** [comment]
Should note this is a clean install, very first thing I did was install and activate onepager and this issue is here. no other plugins or themes.

**Comment by christianfroehlichconsulting** [comment]
Did you use?
npm install
bower install
composer install
gulp

**Comment by codexpert** [comment]
`npm install ~ gulp` not necessary if you are installing the plugin from WP admin.

**Comment by codexpert** [comment]
@anakinjay Can you PM your site details on our Gitter chat ?

**Comment by kimico** [comment]
Same issue, 
v: 1.2.5
wp: 4.7.3–pt_PT

**Comment by felipedeboni** [comment]
@codexpert it happens when the template overwrite the ```onepage.php```, then the dropdown value become ```onepager/onepage.php```.

I've added to quick tests in the meta.js file.

```js
// ...

function enableOnepagerHandler() {
  if ($pageTemplate.find('option[value="onepager/onepage.php"]').get(0)) {
    $pageTemplate.val("onepager/onepage.php");
  } else {
    $pageTemplate.val("onepage.php");
  }

  $pageTemplate.trigger('change');

  $publish.click();
}

// ...

function isOnepageTemplate(template) {
    //if template is null return false
    return template && ("onepage.php" === template || template.indexOf("onepager-") === 0 || template.indexOf("onepager/") === 0);
}

// ...
```
