### ISSUE TITLE
Multilanguage translatable

### ISSUE THREAD

**Issue by biko8** [themexpert/onepager#136]
Is this pluguin translatavle? How can I have same page in two different languages? And one lang selector to chane between they?

**Comment by biko8** [comment]
Any?

**Comment by DavidBruchmann** [comment]
It's quite simple, you just make for every language a different page and
adjust the links to each other.
Even a on-site-language-menu can be used like that.

**Comment by biko8** [comment]
Thank you very much @DavidBruchmann for your answer! I think... is the unique option!
