### ISSUE TITLE
Wordpress default menu system not working properly with onepager

### ISSUE THREAD

**Issue by nadimtuhin** [themexpert/onepager#2]

**Comment by arifulalam** [comment]
Hello,
I think currently working fine in tx-onepager as I used that and there is error found now. :)

*\* But footer Menu not working.

Thanks for that help.

Regards

**Comment by codexpert** [comment]
Yeah its working fine for me too. Seems issue with any 3pd plugins.

**Comment by nadimtuhin** [comment]
@arifulalam your issue is fixed check #7 :)

**Comment by arifulalam** [comment]
where to download it now? Is downloading this github ok? @nadimtuhin

**Comment by nadimtuhin** [comment]
https://www.dropbox.com/s/0b3camvydmstd5v/tx-onepager.zip

**Comment by codexpert** [comment]
Fix https://github.com/themexpert/onepager/commit/512093bce27845da4ac32fc5462804c86b50ea2e

**Comment by mazharvai007** [comment]
thanks for solve this issue
