### ISSUE TITLE
Need global settings api

### ISSUE THREAD

**Issue by mazharvai007** [themexpert/onepager#49]
How can I make theme admin panel as option tree or redux framework ? please give me a suggestion.

**Comment by codexpert** [comment]
Forget about backend option panel. We focus only and only on frontend. Our global settings api is for that. See example here https://github.com/themexpert/onepager/blob/develop/app/OptionsPanel/settings.php

**Comment by swopnil** [comment]
thanks viya

**Comment by mazharvai007** [comment]
thanks @codexpert vai

**Comment by nadimtuhin** [comment]
#48
