### ISSUE TITLE
Editing blocks via HTML/CSS/JS

### ISSUE THREAD

**Issue by halo0477** [themexpert/onepager#53]
Hey guys,

would be great if you could add an section in the OnePager interface to edit the HTML/CSS/JS of any created block.

https://github.com/themexpert/onepager/wiki/How-to-extend-a-block-inside-theme
We're worried about changing the files via FTP and getting problems with new OnePager updates afterwards.

Thanks!
Best regards

**Comment by nadimtuhin** [comment]
@halo0477 if you extend your block from your theme nothing will be removed from onepager update. Or if you add new blocks from themes or plugins they will also not be removed. So feel free to do anything with them.

Though we are talking this issue seriously to let developers edit/update blocks from onepager. Hopefully in 1.1
