### ISSUE TITLE
Adding redirect link options to certain blocks?

### ISSUE THREAD

**Issue by shalaaa** [themexpert/onepager#70]
Is it possible to add a redirect link to a specific webpage in place of the "click to enlarge picture" in the "What We Do" Portfolio-1 block? I can see so much potential there.

**Comment by codexpert** [comment]
Yes you can do that. You just need to overwrite the block file and functionality you want without hacking the core code.

**Comment by nadimtuhin** [comment]
:) added will be available in 1.2.4 soon
