### ISSUE TITLE
Register new preset not working when disable preset code is on

### ISSUE THREAD

**Issue by themefisher** [themexpert/onepager#73]
If i write

```
Onepager::disableCorePresets(); 
```

I can't register my preset folder
`Onepager::registerPresets();` or `Onepager::registerPresets('MYFOLDER');`

**Comment by nadimtuhin** [comment]
thanks will be patched in 1.1.5

**Comment by nadimtuhin** [comment]
fixed in d0bf5c180642ed28a6331b3943ea3a1e6fbb91d8
