### ISSUE TITLE
Testimonial slider goes very fast

### ISSUE THREAD

**Issue by albertheres** [themexpert/onepager#81]
Hello onepager Team,

I think it will be usefull to make the portfolio sliding time adjustable. Now it goes very fast. And in my case it is not possible to read a paragraph of 60 words.

Best regards,
Albert

**Comment by nadimtuhin** [comment]
good catch we will put this option in next release. btw is it slider-1 block that you are talking about?

**Comment by nadimtuhin** [comment]
and if you are a developer we will be glad if you could help. these are the files that need to be changed.

https://github.com/themexpert/onepager/blob/develop/blocks%2Fsliders%2Fslider-1%2Fview.php
https://github.com/themexpert/onepager/blob/develop/blocks%2Fsliders%2Fslider-1%2Fconfig.php

**Comment by albertheres** [comment]
Hello,

I'm talking about testimonial-1 (What we do). The term portfolio in my first post was a mistake.

I'm sorry, I'm not a developer. But I will take a look to the php files.

**Comment by nadimtuhin** [comment]
no worries :+1:  we will be adding this into v1.2 release this week

**Comment by albertheres** [comment]
Great, thanks!

**Comment by albertheres** [comment]
Hello,

Thanks for adding the slider interval in 1.2.1. I tried to adjust the slider interval. But unfortunately nothing happens. After saving and viewing the page the slide value goes automatically back to "3".

**Comment by nadimtuhin** [comment]
thanks for reporting we are working on it

**Comment by nadimtuhin** [comment]
https://www.dropbox.com/s/4m14jdb56112b8i/onepager.zip download this and unzip in your current theme directory. We will be including this patch in our next release v1.2.3

**Comment by albertheres** [comment]
Thanks!

**Comment by nadimtuhin** [comment]
welcome :+1:

**Comment by albertheres** [comment]
I just update to 1.2.3. The slider interval works! There is only one issue. After changing the value, saving and viewing the value goes automatically back to 3.

**Comment by nadimtuhin** [comment]
@albertheres we have not released v1.2.3 yet. You will be using v1.2.2 and upload the files I sent you in your wordpress theme folder after unzipping it. https://www.dropbox.com/s/4m14jdb56112b8i/onepager.zip

**Comment by albertheres** [comment]
Okay clear. Thanks!

**Comment by nadimtuhin** [comment]
Great. Do let us know if you were successful.
