### ISSUE TITLE
Drop-down lists within the builder

### ISSUE THREAD

**Issue by alanji** [themexpert/onepager#83]
There are a number of drop-down lists within the builder. They initially worked. However, after a couple of days, they stopped working, meaning, when I click the arrow, the list no longer drop down.

Please help.

**Comment by nadimtuhin** [comment]
@alanji sorry for your problem, please answer them
1. Are you using latest version http://wordpress.org/plugins/tx-onepager/ ? if not follow step 2
2. You said the dropdowns initially worked then stopped. There could be reasons like
  a. Try switching theme if it fixes the problem let us know.
  b. Try creating a new page and enable onepager. See if it fixes the problem
3. Open browser console emulator and attach a screenshot.

**Comment by alanji** [comment]
Thanks Nadim. Switching to a different theme fixed my drop-down list issue.

Alan

**Comment by nadimtuhin** [comment]
You are welcome. Also in our next release you will not face this issue with any theme or plugin :)
