### ISSUE TITLE
Can't access to a Onepager page

### ISSUE THREAD

**Issue by damienroue** [themexpert/onepager#85]
I created a page with Onepager. Everything has been working fine since yesterday. The page is not longer "Onepaged" and appears empty (as the content is not in the wordpress page but in Onepager). Is this a known issue? Do you know how I can recover all the informations from the Onepage I created so I can duplicate it on another clean page?

Thanks

**Comment by nadimtuhin** [comment]
@damienroue this is a weird. We have not faced anything such. There is no way content of page will be gone. Did you blank your template by clicking on the start blank preset 
![download](https://cloud.githubusercontent.com/assets/3125771/10305008/60d22d1c-6c3f-11e5-977c-4936d31a0493.png)

**Comment by damienroue** [comment]
No I haven't blanked the content on this page. I may have change attributes
and custom fields of the page though. I recovered the data in MySQL.

## 

Damien

**Comment by nadimtuhin** [comment]
@damienroue onepager saves your content in custom fields. So its possible that they might have been over written then. A recovery should work if there is.

Let us know if we could help with anything else.

**Comment by damienroue** [comment]
I'm having the same problem with the page I just recreated from scratch.
I'll wait for your v1.2 to see if this solves the problem.

Bests,

## 

Damien

**Comment by nadimtuhin** [comment]
@damienroue can you provide us with admin access to your site? It will be great help for us to see if this is really an issue with onepager. You can mail your credential to nadimtuhin at themexpert.com if you want.

**Comment by damienroue** [comment]
I found a way to reproduce: when I create the page for the first time,
that's ok. But if I update it it no longer keeps the Onepager page type.

Le mar. 6 oct. 2015 à 11:48, Nadim Tuhin notifications@github.com a
écrit :

**Comment by nadimtuhin** [comment]
Thanks we are working on it.

On Tue, Oct 6, 2015 at 4:55 PM, Damien Roué notifications@github.com
wrote:

> I found a way to reproduce: when I create the page for the first time,
> that's ok. But if I update it it no longer keeps the Onepager page type.
> 
> Le mar. 6 oct. 2015 à 11:48, Nadim Tuhin notifications@github.com a
> écrit :
> 
> > @damienroue https://github.com/damienroue can you provide us with
> > admin
> > access to your site? It will be great help for us to see if this is
> > really
> > an issue with onepager. You can mail your credential to
> > nadimtuhin@themexpert.com if you want.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/themexpert/onepager/issues/85#issuecomment-145802136
> > .
> > Untracked with Trackbuster <https://trackbuster.com/?sig>
> > 
> > ## 
> > 
> > -Damien
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/themexpert/onepager/issues/85#issuecomment-145821418.

## 

Regards,
Omar Faruque Tuhin,

Software Engineer,
ThemeXpert

**Comment by nadimtuhin** [comment]
Its taking sometime. Still figuring out which plugin causing the problem.

**Comment by damienroue** [comment]
Hi Nadim, congrats for the new release.
Any update on this?

**Comment by nadimtuhin** [comment]
@damienroue sorry we could not find a solution yet. I will let you know personally in 3 days.

**Comment by nadimtuhin** [comment]
https://www.dropbox.com/s/aoqxtuthp3x63mh/tx-onepager-1.2.4-beta1.zip?dl=1 please try this beta

**Comment by damienroue** [comment]
I just tried out the beta, problem not solved

**Comment by nadimtuhin** [comment]
@damienroue sorry to hear that. On my machine I found no problem with the theme+plugin combination. Lets try something else 
https://github.com/themexpert/onepager/blob/develop/app%2Ftemplates%2Fonepage.php put this file in your theme directory

**Comment by damienroue** [comment]
Thanks to that I have now access to the editor, I’ll see if I can publish a page with this version, thanks!

**Comment by nadimtuhin** [comment]
great still it hurts not being able to solve the problem directly :/ Are you using any special wordpress directory structure?

**Comment by damienroue** [comment]
Nothing special.
