### ISSUE TITLE
Onepager breaking search results page

### ISSUE THREAD

**Issue by damienroue** [themexpert/onepager#86]
Onepager 1.1.4 is breaking the search results page on my site

with the plugin
![withonepager](https://cloud.githubusercontent.com/assets/2393883/10306877/4c77c846-6c2a-11e5-9dd9-f93a102a78d4.jpg)
without the plugin
![withoutonepager](https://cloud.githubusercontent.com/assets/2393883/10306878/4c94b848-6c2a-11e5-8f80-4f21f8e8dd1f.jpg)

Theme is Hickory http://solopine.com/theme/hickory/

**Comment by nadimtuhin** [comment]
Wow this is a real problem. We are checking it out. Thanks a lot for
reporting.

On Tue, Oct 6, 2015 at 5:04 PM, Damien Roué notifications@github.com
wrote:

> Onepager 1.1.4 is breaking the search results page on my site
> 
> with the plugin
> [image: withonepager]
> https://cloud.githubusercontent.com/assets/2393883/10306877/4c77c846-6c2a-11e5-9dd9-f93a102a78d4.jpg
> without the plugin
> [image: withoutonepager]
> https://cloud.githubusercontent.com/assets/2393883/10306878/4c94b848-6c2a-11e5-8f80-4f21f8e8dd1f.jpg
> 
> Theme is Hickory http://solopine.com/theme/hickory/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/themexpert/onepager/issues/86.

## 

Regards,
Omar Faruque Tuhin,

Software Engineer,
ThemeXpert

**Comment by damienroue** [comment]
I'm trying to investigate it, I found something and I should dig deeper.

**Comment by damienroue** [comment]
Ok the bug is a combination of my wordpress theme and a page without cover image referenced in the search results. So the bug is not entirely due to Onepager but it happens only when Onepager is activated, even if this page is not using the plugin.

**Comment by nadimtuhin** [comment]
@damienroue its fixed :) in 1.2
