### ISSUE TITLE
style.css over write feature.

### ISSUE THREAD

**Issue by ashikrnhq04** [themexpert/onepager#87]
Hi! Please add plug-in default style.css over write features and add icon feature instead of image in feature block content. or keep booth feature

**Comment by nadimtuhin** [comment]
feature addedd in these commits 551edf0018490457e72e7b4daec94b41b6968aa7 43a31985a33029cebe806503eff8220ffe26fe1a will be available from v1.2

How to use

my-theme/onepager/overrides/block-slug/block.css
my-theme/onepager/overrides/block-slug/view.php
my-theme/onepager/overrides/block-slug/style.php
