### ISSUE TITLE
Editor doesn't open

### ISSUE THREAD

**Issue by albertheres** [themexpert/onepager#95]
Hello,

Thanks for version 1.2.1. Great that the silder interval is added!

I tried to open de editor of my homepage, but unfortunately is doesn't load anymore. Still a black page is appears.

Do you know what's going wrong?

Best regards,
Albert

**Comment by nadimtuhin** [comment]
Sorry you had problems :( . Please delete the plugin and install again and
let us know if everything is fine.

On Tue, Oct 13, 2015 at 6:09 PM, albertheres notifications@github.com
wrote:

> Hello,
> 
> Thanks for version 1.2.1. Great that the silder interval is added!
> 
> I tried to open de editor of my homepage, but unfortunately is doesn't
> load anymore. Still a black page is appears.
> 
> Do you know what's going wrong?
> 
> Best regards,
> Albert
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/themexpert/onepager/issues/95.

## 

Regards,
Omar Faruque Tuhin,

Software Engineer,
ThemeXpert

**Comment by nadimtuhin** [comment]
also can you share your website url through email? nadimtuhin@themexpert.com

**Comment by albertheres** [comment]
Thanks for your reply.

After deleting 1.2.1 and installing version 1.1.4 everything works fine.

**Comment by nadimtuhin** [comment]
@albertheres please try installing 1.2.1 again from wordpress repo

**Comment by albertheres** [comment]
I have installed it again from repo but no solution. For your information the homepage is visible in the front end but only in the back end editor it gives a blank page.

**Comment by nadimtuhin** [comment]
@albertheres is it possible for you to give me your admin access? if possible please send me the access to nadimtuhin@themexpert.com

**Comment by nadimtuhin** [comment]
fixed in f36ba21a0c7595a8af63adf9c991fd75944c22d4
