### ISSUE TITLE
OnePager support for Roots.io

### ISSUE THREAD

**Issue by perroud** [themexpert/onepager#96]
Hello,
**Can you improve [Sage Starter Theme](https://roots.io/sage/) support, please?** Including [Bedrock](https://roots.io/bedrock/) support, if possible. I do not know about [Bedrock](https://github.com/roots/bedrock), having a custom directory structure.

With [Sage](https://github.com/roots/sage), Bootstrap by default, like OnePager. What about [Gromf](https://github.com/schikulski/gromf) (Sage + Foundation5) and [Sage MDL](https://github.com/peiche/sage-mdl) (Sage + Material Design Lite)?

Anyone have used [HTML5BLANK Theme](http://html5blank.com/) with OnePager?

**Comment by nadimtuhin** [comment]
sage support is given on 1.2.3

**Comment by perroud** [comment]
@nadimtuhin Thank you very much.
