### ISSUE TITLE
Add Clickable Links

### ISSUE THREAD

**Issue by JPACE5** [themexpert/onepager#98]
Please add the capability to insert URLs to thumnails in Portfolio, Team, and Features block thumbnails. This would work similarly to the Call to Action block, except there would be a link capability for each thumbnail. 

Thank you.

**Comment by JakeHenshall** [comment]
+1

**Comment by nadimtuhin** [comment]
Lots of blocks needs this change. So we scheduled this for 1.2.4

**Comment by JPACE5** [comment]
Thank you for your response. I have two websites that I am going to soon be updating. Do you have a date of when 1.2.4 will be complete/implemented? Thanks.

**Comment by nadimtuhin** [comment]
@JPACE5 by this sunday

**Comment by nadimtuhin** [comment]
added :)
